[project]
name = "biautils"
version = "0.2.0"
description = "biautils compute environment for computational microscopy at CZBiohub SF"
authors = ["CZ Biohub and iohub contributors <cm-biautils@czbiohub.org>"]
channels = ["conda-forge", "nvidia", "pytorch", "numba", "rapidsai"]
platforms = ["linux-64"]

[tasks]
env-info = { cmd = "env_info" }
start-napari = { cmd = "napari"}

[system-requirements]
cuda = "12"

[dependencies]
# Python runtime
python = "==3.11"
scipy = "<1.16" # scipy <1.16 for biahub compatibility
cupy = "*"
cucim = "*"
pytorch-cuda = "==12.4"
catboost = "*"
scikit-learn = "*"
ffmpeg = "*" # napari-animation requires ffmpeg

[pypi-dependencies]
napari = {extras = ["pyqt6"]}
napari-iohub = { git = "https://github.com/czbiohub-sf/napari-iohub" }
napari-ome-zarr = {version = ">=0.6.1"}
napari-animation = {version = ">=0.0.9"}
biahub = { git = "https://github.com/czbiohub-sf/biahub" }
ultrack = { git = "https://github.com/royerlab/ultrack"}
waveorder = { version = ">=3.0.0a1", extras = ["all"] }
viscy = ">=0.3.2"
rich = ">=13.0.0"
biautils = { path = "."}

[environments]
# Default environment - full HPC environment
default = { features = [] }

